Add support for discount links
instantcommerce/shopify-headless-theme pull request #17
Opened 2023-04-20 18:13 UTC by benjaminsehl

Fixes #16

2023-04-20 18:34 UTC, benjaminsehl commented
Note this doesn't actually magically add discount applications to your headless site, you'd still need to grab the search param, and then save it as a cookie (or similar) and then apply the discount when you create the cart.

2023-04-21 08:52 UTC, leeuwis requested changes
@benjaminsehl thank you for taking the time to create the issue and the PR 💯 

I found one part in the code that seems redundant, after that's removed it can be merged

> Note this doesn't actually magically add discount applications to your headless site, you'd still need to grab the search param, and then save it as a cookie (or similar) and then apply the discount when you create the cart.

Yes, makes sense. That's applicable for most logic that happens in this theme 👌

2023-04-21 08:52 UTC, leeuwis commented on theme/layout/theme.liquid
> +
Seems like this part is not being used, can be removed:

```suggestion    
```

2023-04-21 10:29 UTC, benjaminsehl commented
> I found one part in the code that seems redundant, after that's removed it can be merged

Ah yes good catch! Fixed

2023-04-21 12:23 UTC, leeuwis approved these changes

2023-04-21 12:23 UTC, merged